### ISSUE TITLE
Better Conversation Handling between App and Dgraph backend

### ISSUE THREAD

**Issue by istos** [opendialogai/core#194]
The integration between the admin of conversations and Dgraph is very rudimentary and can easily lead to inconsistencies between the state of conversations in the app admin and Dgraph. 

Related Issues:
#193 
#157 
#114 

We need to define the desired behaviour and work towards that.

**Comment by istos** [comment]
[Conversation Lifecycle.pdf](https://github.com/opendialogai/core/files/3534671/Conversation.Lifecycle.pdf)

Attaching some initial ideas around lifecycle and conversation model as well as notes on the interface

**Comment by istos** [comment]
@elliotmassen over to you for an initial review and scoping exercise.

**Comment by elliotmassen** [comment]
Here's a review of the areas of the codebase that would be affected by these updates, along with some points for further consideration.

## Review of changes

### opendialogai/core

*   ConversationEngine/ConversationStore/(DGraphConversationStore,DGraphQueries):
    *   Account for new conversation template states to ensure that queries are only returning the current active conversation template (when applicable).
*   Graph/DGraph/DGraphQuery:
    *   Add support for query filter connectives to allow for additional filtering by conversation state and/or conversation version number, eg `@filter(eq(ei_type, 'conversation_template') and eq(conversation_state, 'activated'))`. This will require changes/additions to the preparation and generation of DGraph queries.
        *   As an optional consideration, it may also be worth looking at adding support for specifying predicates to order results by, as well as basic pagination support by adding support for `first`. This would make querying conversation version history easier and give us easy certainty that we have the latest active version of a conversation. Adding this support to our DGraph integration allows us to avoid pulling all of a conversation’s version history only to disregard most of it, or have to use PHP to sort the versions by version number, which may cause inefficiencies as a version history grows.
*   Conversation/Conversation:
    *   Add attributes & accessors methods for the following:
        *   Conversation template state
        *   Conversation version number
        *   Instance of (conversation user & conversation template relation)
        *   Update of (conversation template version relation)
    *   Functionality to return an ordered list of conversation template version history
*   Console/Commands/(ImportConversations,ExportConversations):
    *   Since we are going to be adding version history to MySQL, we will need to update queries in the commands as they rely on there only being one record per conversation name.
*   ConversationBuilder/Conversation:
    *   Rename publish to activate
    *   Activating one version of the conversation template should deactivate all other versions
    *   Add methods for:
        *   Archiving a version
        *   Deleting a version
        *   Retrieving a list of previous (undeleted) versions

### opendialogai/opendialog

*   app/Http/Controllers/API/ConversationsController,ConversationBuilder/Conversation:
    *   Rename publish to activate
    *   Add methods for:
        *   Archiving a version
        *   Deleting a version
        *   Retrieving a list of previous (undeleted) versions

## Questions/Require further consideration

1. We discussed yesterday that deactivating a conversation template should provide the admin with an option to kick users off the previous conversation or to allow them to continue on the outdated version. We should discuss this a little more to figure out the expected behaviour & outcomes.
2. Yesterday @stu-greenshoots mentioned that we will need to consider locking/transactions on DGraph updates to ensure states (activated/deactivated) are properly managed. It is also worth considering whether we need to introduce some sort of bulk management of conversation history to enforce a constraint of only allowing one active conversation template at a time.
